/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as KioskRouteRouteImport } from './routes/_kiosk/route'
import { Route as KioskIndexRouteImport } from './routes/_kiosk/index'
import { Route as KioskNavigatorRouteImport } from './routes/_kiosk/navigator'
import { Route as KioskTvRouteImport } from './routes/_kiosk/tv'

const KioskRouteRoute = KioskRouteRouteImport.update({
  id: '/_kiosk',
  getParentRoute: () => rootRouteImport,
} as any)
const KioskIndexRoute = KioskIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => KioskRouteRoute,
} as any)
const KioskNavigatorRoute = KioskNavigatorRouteImport.update({
  id: '/navigator',
  path: '/navigator',
  getParentRoute: () => KioskRouteRoute,
} as any)
const KioskTvRoute = KioskTvRouteImport.update({
  id: '/tv',
  path: '/tv',
  getParentRoute: () => KioskRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof KioskIndexRoute
  '/navigator': typeof KioskNavigatorRoute
  '/tv': typeof KioskTvRoute
}
export interface FileRoutesByTo {
  '/navigator': typeof KioskNavigatorRoute
  '/tv': typeof KioskTvRoute
  '/': typeof KioskIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_kiosk': typeof KioskRouteRouteWithChildren
  '/_kiosk/navigator': typeof KioskNavigatorRoute
  '/_kiosk/tv': typeof KioskTvRoute
  '/_kiosk/': typeof KioskIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/navigator' | '/tv'
  fileRoutesByTo: FileRoutesByTo
  to: '/navigator' | '/tv' | '/'
  id: '__root__' | '/_kiosk' | '/_kiosk/navigator' | '/_kiosk/tv' | '/_kiosk/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  KioskRouteRoute: typeof KioskRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_kiosk': {
      id: '/_kiosk'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof KioskRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_kiosk/': {
      id: '/_kiosk/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof KioskIndexRouteImport
      parentRoute: typeof KioskRouteRoute
    }
    '/_kiosk/navigator': {
      id: '/_kiosk/navigator'
      path: '/navigator'
      fullPath: '/navigator'
      preLoaderRoute: typeof KioskNavigatorRouteImport
      parentRoute: typeof KioskRouteRoute
    }
    '/_kiosk/tv': {
      id: '/_kiosk/tv'
      path: '/tv'
      fullPath: '/tv'
      preLoaderRoute: typeof KioskTvRouteImport
      parentRoute: typeof KioskRouteRoute
    }
  }
}

interface KioskRouteRouteChildren {
  KioskNavigatorRoute: typeof KioskNavigatorRoute
  KioskTvRoute: typeof KioskTvRoute
  KioskIndexRoute: typeof KioskIndexRoute
}

const KioskRouteRouteChildren: KioskRouteRouteChildren = {
  KioskNavigatorRoute: KioskNavigatorRoute,
  KioskTvRoute: KioskTvRoute,
  KioskIndexRoute: KioskIndexRoute,
}

const KioskRouteRouteWithChildren = KioskRouteRoute._addFileChildren(
  KioskRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  KioskRouteRoute: KioskRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
