contact_links:
  - name: Ask a question
    url: https://github.com/filcdev/filc/issues/new/choose
    about: Ask questions and discuss with other community members
  - name: Feature request
    url: https://github.com/filcdev/filc/issues/new/choose
    about: Feature requests should be opened as discussions
