services:
  proxy:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./logs:/var/log/nginx

  landing:
    image: ghcr.io/filcdev/filc:landing
    restart: unless-stopped

  web:
    image: ghcr.io/filcdev/filc:web
    restart: unless-stopped

  server:
    image: ghcr.io/filcdev/filc:server
    restart: unless-stopped
