/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PublicRouteRouteImport } from './routes/_public/route'
import { Route as PrivateRouteRouteImport } from './routes/_private/route'
import { Route as PublicIndexRouteImport } from './routes/_public/index'
import { Route as AuthWelcomeRouteImport } from './routes/auth/welcome'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AuthErrorRouteImport } from './routes/auth/error'
import { Route as PrivateProbaRouteImport } from './routes/_private/proba'
import { Route as PrivateAdminRouteRouteImport } from './routes/_private/admin/route'
import { Route as PrivateAdminUsersRouteImport } from './routes/_private/admin/users'
import { Route as PrivateAdminDoorlockIndexRouteImport } from './routes/_private/admin/doorlock/index'
import { Route as PrivateAdminTimetableImportRouteImport } from './routes/_private/admin/timetable/import'
import { Route as PrivateAdminDoorlockLogsRouteImport } from './routes/_private/admin/doorlock/logs'
import { Route as PrivateAdminDoorlockDevicesRouteImport } from './routes/_private/admin/doorlock/devices'
import { Route as PrivateAdminDoorlockCardsRouteImport } from './routes/_private/admin/doorlock/cards'

const PublicRouteRoute = PublicRouteRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivateRouteRoute = PrivateRouteRouteImport.update({
  id: '/_private',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRouteRoute,
} as any)
const AuthWelcomeRoute = AuthWelcomeRouteImport.update({
  id: '/auth/welcome',
  path: '/auth/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthErrorRoute = AuthErrorRouteImport.update({
  id: '/auth/error',
  path: '/auth/error',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivateProbaRoute = PrivateProbaRouteImport.update({
  id: '/proba',
  path: '/proba',
  getParentRoute: () => PrivateRouteRoute,
} as any)
const PrivateAdminRouteRoute = PrivateAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => PrivateRouteRoute,
} as any)
const PrivateAdminUsersRoute = PrivateAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => PrivateAdminRouteRoute,
} as any)
const PrivateAdminDoorlockIndexRoute =
  PrivateAdminDoorlockIndexRouteImport.update({
    id: '/doorlock/',
    path: '/doorlock/',
    getParentRoute: () => PrivateAdminRouteRoute,
  } as any)
const PrivateAdminTimetableImportRoute =
  PrivateAdminTimetableImportRouteImport.update({
    id: '/timetable/import',
    path: '/timetable/import',
    getParentRoute: () => PrivateAdminRouteRoute,
  } as any)
const PrivateAdminDoorlockLogsRoute =
  PrivateAdminDoorlockLogsRouteImport.update({
    id: '/doorlock/logs',
    path: '/doorlock/logs',
    getParentRoute: () => PrivateAdminRouteRoute,
  } as any)
const PrivateAdminDoorlockDevicesRoute =
  PrivateAdminDoorlockDevicesRouteImport.update({
    id: '/doorlock/devices',
    path: '/doorlock/devices',
    getParentRoute: () => PrivateAdminRouteRoute,
  } as any)
const PrivateAdminDoorlockCardsRoute =
  PrivateAdminDoorlockCardsRouteImport.update({
    id: '/doorlock/cards',
    path: '/doorlock/cards',
    getParentRoute: () => PrivateAdminRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/admin': typeof PrivateAdminRouteRouteWithChildren
  '/proba': typeof PrivateProbaRoute
  '/auth/error': typeof AuthErrorRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/welcome': typeof AuthWelcomeRoute
  '/': typeof PublicIndexRoute
  '/admin/users': typeof PrivateAdminUsersRoute
  '/admin/doorlock/cards': typeof PrivateAdminDoorlockCardsRoute
  '/admin/doorlock/devices': typeof PrivateAdminDoorlockDevicesRoute
  '/admin/doorlock/logs': typeof PrivateAdminDoorlockLogsRoute
  '/admin/timetable/import': typeof PrivateAdminTimetableImportRoute
  '/admin/doorlock': typeof PrivateAdminDoorlockIndexRoute
}
export interface FileRoutesByTo {
  '/admin': typeof PrivateAdminRouteRouteWithChildren
  '/proba': typeof PrivateProbaRoute
  '/auth/error': typeof AuthErrorRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/welcome': typeof AuthWelcomeRoute
  '/': typeof PublicIndexRoute
  '/admin/users': typeof PrivateAdminUsersRoute
  '/admin/doorlock/cards': typeof PrivateAdminDoorlockCardsRoute
  '/admin/doorlock/devices': typeof PrivateAdminDoorlockDevicesRoute
  '/admin/doorlock/logs': typeof PrivateAdminDoorlockLogsRoute
  '/admin/timetable/import': typeof PrivateAdminTimetableImportRoute
  '/admin/doorlock': typeof PrivateAdminDoorlockIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_private': typeof PrivateRouteRouteWithChildren
  '/_public': typeof PublicRouteRouteWithChildren
  '/_private/admin': typeof PrivateAdminRouteRouteWithChildren
  '/_private/proba': typeof PrivateProbaRoute
  '/auth/error': typeof AuthErrorRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/welcome': typeof AuthWelcomeRoute
  '/_public/': typeof PublicIndexRoute
  '/_private/admin/users': typeof PrivateAdminUsersRoute
  '/_private/admin/doorlock/cards': typeof PrivateAdminDoorlockCardsRoute
  '/_private/admin/doorlock/devices': typeof PrivateAdminDoorlockDevicesRoute
  '/_private/admin/doorlock/logs': typeof PrivateAdminDoorlockLogsRoute
  '/_private/admin/timetable/import': typeof PrivateAdminTimetableImportRoute
  '/_private/admin/doorlock/': typeof PrivateAdminDoorlockIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/admin'
    | '/proba'
    | '/auth/error'
    | '/auth/login'
    | '/auth/welcome'
    | '/'
    | '/admin/users'
    | '/admin/doorlock/cards'
    | '/admin/doorlock/devices'
    | '/admin/doorlock/logs'
    | '/admin/timetable/import'
    | '/admin/doorlock'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/admin'
    | '/proba'
    | '/auth/error'
    | '/auth/login'
    | '/auth/welcome'
    | '/'
    | '/admin/users'
    | '/admin/doorlock/cards'
    | '/admin/doorlock/devices'
    | '/admin/doorlock/logs'
    | '/admin/timetable/import'
    | '/admin/doorlock'
  id:
    | '__root__'
    | '/_private'
    | '/_public'
    | '/_private/admin'
    | '/_private/proba'
    | '/auth/error'
    | '/auth/login'
    | '/auth/welcome'
    | '/_public/'
    | '/_private/admin/users'
    | '/_private/admin/doorlock/cards'
    | '/_private/admin/doorlock/devices'
    | '/_private/admin/doorlock/logs'
    | '/_private/admin/timetable/import'
    | '/_private/admin/doorlock/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  PrivateRouteRoute: typeof PrivateRouteRouteWithChildren
  PublicRouteRoute: typeof PublicRouteRouteWithChildren
  AuthErrorRoute: typeof AuthErrorRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthWelcomeRoute: typeof AuthWelcomeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof PublicRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_private': {
      id: '/_private'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof PrivateRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/auth/welcome': {
      id: '/auth/welcome'
      path: '/auth/welcome'
      fullPath: '/auth/welcome'
      preLoaderRoute: typeof AuthWelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/error': {
      id: '/auth/error'
      path: '/auth/error'
      fullPath: '/auth/error'
      preLoaderRoute: typeof AuthErrorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_private/proba': {
      id: '/_private/proba'
      path: '/proba'
      fullPath: '/proba'
      preLoaderRoute: typeof PrivateProbaRouteImport
      parentRoute: typeof PrivateRouteRoute
    }
    '/_private/admin': {
      id: '/_private/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof PrivateAdminRouteRouteImport
      parentRoute: typeof PrivateRouteRoute
    }
    '/_private/admin/users': {
      id: '/_private/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof PrivateAdminUsersRouteImport
      parentRoute: typeof PrivateAdminRouteRoute
    }
    '/_private/admin/doorlock/': {
      id: '/_private/admin/doorlock/'
      path: '/doorlock'
      fullPath: '/admin/doorlock'
      preLoaderRoute: typeof PrivateAdminDoorlockIndexRouteImport
      parentRoute: typeof PrivateAdminRouteRoute
    }
    '/_private/admin/timetable/import': {
      id: '/_private/admin/timetable/import'
      path: '/timetable/import'
      fullPath: '/admin/timetable/import'
      preLoaderRoute: typeof PrivateAdminTimetableImportRouteImport
      parentRoute: typeof PrivateAdminRouteRoute
    }
    '/_private/admin/doorlock/logs': {
      id: '/_private/admin/doorlock/logs'
      path: '/doorlock/logs'
      fullPath: '/admin/doorlock/logs'
      preLoaderRoute: typeof PrivateAdminDoorlockLogsRouteImport
      parentRoute: typeof PrivateAdminRouteRoute
    }
    '/_private/admin/doorlock/devices': {
      id: '/_private/admin/doorlock/devices'
      path: '/doorlock/devices'
      fullPath: '/admin/doorlock/devices'
      preLoaderRoute: typeof PrivateAdminDoorlockDevicesRouteImport
      parentRoute: typeof PrivateAdminRouteRoute
    }
    '/_private/admin/doorlock/cards': {
      id: '/_private/admin/doorlock/cards'
      path: '/doorlock/cards'
      fullPath: '/admin/doorlock/cards'
      preLoaderRoute: typeof PrivateAdminDoorlockCardsRouteImport
      parentRoute: typeof PrivateAdminRouteRoute
    }
  }
}

interface PrivateAdminRouteRouteChildren {
  PrivateAdminUsersRoute: typeof PrivateAdminUsersRoute
  PrivateAdminDoorlockCardsRoute: typeof PrivateAdminDoorlockCardsRoute
  PrivateAdminDoorlockDevicesRoute: typeof PrivateAdminDoorlockDevicesRoute
  PrivateAdminDoorlockLogsRoute: typeof PrivateAdminDoorlockLogsRoute
  PrivateAdminTimetableImportRoute: typeof PrivateAdminTimetableImportRoute
  PrivateAdminDoorlockIndexRoute: typeof PrivateAdminDoorlockIndexRoute
}

const PrivateAdminRouteRouteChildren: PrivateAdminRouteRouteChildren = {
  PrivateAdminUsersRoute: PrivateAdminUsersRoute,
  PrivateAdminDoorlockCardsRoute: PrivateAdminDoorlockCardsRoute,
  PrivateAdminDoorlockDevicesRoute: PrivateAdminDoorlockDevicesRoute,
  PrivateAdminDoorlockLogsRoute: PrivateAdminDoorlockLogsRoute,
  PrivateAdminTimetableImportRoute: PrivateAdminTimetableImportRoute,
  PrivateAdminDoorlockIndexRoute: PrivateAdminDoorlockIndexRoute,
}

const PrivateAdminRouteRouteWithChildren =
  PrivateAdminRouteRoute._addFileChildren(PrivateAdminRouteRouteChildren)

interface PrivateRouteRouteChildren {
  PrivateAdminRouteRoute: typeof PrivateAdminRouteRouteWithChildren
  PrivateProbaRoute: typeof PrivateProbaRoute
}

const PrivateRouteRouteChildren: PrivateRouteRouteChildren = {
  PrivateAdminRouteRoute: PrivateAdminRouteRouteWithChildren,
  PrivateProbaRoute: PrivateProbaRoute,
}

const PrivateRouteRouteWithChildren = PrivateRouteRoute._addFileChildren(
  PrivateRouteRouteChildren,
)

interface PublicRouteRouteChildren {
  PublicIndexRoute: typeof PublicIndexRoute
}

const PublicRouteRouteChildren: PublicRouteRouteChildren = {
  PublicIndexRoute: PublicIndexRoute,
}

const PublicRouteRouteWithChildren = PublicRouteRoute._addFileChildren(
  PublicRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  PrivateRouteRoute: PrivateRouteRouteWithChildren,
  PublicRouteRoute: PublicRouteRouteWithChildren,
  AuthErrorRoute: AuthErrorRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthWelcomeRoute: AuthWelcomeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
