/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PublicRouteRouteImport } from './routes/_public/route'
import { Route as PrivateRouteRouteImport } from './routes/_private/route'
import { Route as PublicIndexRouteImport } from './routes/_public/index'
import { Route as AuthWelcomeRouteImport } from './routes/auth/welcome'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AuthErrorRouteImport } from './routes/auth/error'
import { Route as PrivateProbaRouteImport } from './routes/_private/proba'
import { Route as PrivateAdminRouteRouteImport } from './routes/_private/admin/route'
import { Route as PrivateAdminIndexRouteImport } from './routes/_private/admin/index'
import { Route as PrivateAdminLogsRouteImport } from './routes/_private/admin/logs'
import { Route as PrivateAdminDevicesRouteImport } from './routes/_private/admin/devices'
import { Route as PrivateAdminCardsRouteImport } from './routes/_private/admin/cards'
import { Route as PrivateAdminTimetableImportRouteImport } from './routes/_private/admin/timetable/import'

const PublicRouteRoute = PublicRouteRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivateRouteRoute = PrivateRouteRouteImport.update({
  id: '/_private',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRouteRoute,
} as any)
const AuthWelcomeRoute = AuthWelcomeRouteImport.update({
  id: '/auth/welcome',
  path: '/auth/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthErrorRoute = AuthErrorRouteImport.update({
  id: '/auth/error',
  path: '/auth/error',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivateProbaRoute = PrivateProbaRouteImport.update({
  id: '/proba',
  path: '/proba',
  getParentRoute: () => PrivateRouteRoute,
} as any)
const PrivateAdminRouteRoute = PrivateAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => PrivateRouteRoute,
} as any)
const PrivateAdminIndexRoute = PrivateAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PrivateAdminRouteRoute,
} as any)
const PrivateAdminLogsRoute = PrivateAdminLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => PrivateAdminRouteRoute,
} as any)
const PrivateAdminDevicesRoute = PrivateAdminDevicesRouteImport.update({
  id: '/devices',
  path: '/devices',
  getParentRoute: () => PrivateAdminRouteRoute,
} as any)
const PrivateAdminCardsRoute = PrivateAdminCardsRouteImport.update({
  id: '/cards',
  path: '/cards',
  getParentRoute: () => PrivateAdminRouteRoute,
} as any)
const PrivateAdminTimetableImportRoute =
  PrivateAdminTimetableImportRouteImport.update({
    id: '/timetable/import',
    path: '/timetable/import',
    getParentRoute: () => PrivateAdminRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/admin': typeof PrivateAdminRouteRouteWithChildren
  '/proba': typeof PrivateProbaRoute
  '/auth/error': typeof AuthErrorRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/welcome': typeof AuthWelcomeRoute
  '/': typeof PublicIndexRoute
  '/admin/cards': typeof PrivateAdminCardsRoute
  '/admin/devices': typeof PrivateAdminDevicesRoute
  '/admin/logs': typeof PrivateAdminLogsRoute
  '/admin/': typeof PrivateAdminIndexRoute
  '/admin/timetable/import': typeof PrivateAdminTimetableImportRoute
}
export interface FileRoutesByTo {
  '/proba': typeof PrivateProbaRoute
  '/auth/error': typeof AuthErrorRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/welcome': typeof AuthWelcomeRoute
  '/': typeof PublicIndexRoute
  '/admin/cards': typeof PrivateAdminCardsRoute
  '/admin/devices': typeof PrivateAdminDevicesRoute
  '/admin/logs': typeof PrivateAdminLogsRoute
  '/admin': typeof PrivateAdminIndexRoute
  '/admin/timetable/import': typeof PrivateAdminTimetableImportRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_private': typeof PrivateRouteRouteWithChildren
  '/_public': typeof PublicRouteRouteWithChildren
  '/_private/admin': typeof PrivateAdminRouteRouteWithChildren
  '/_private/proba': typeof PrivateProbaRoute
  '/auth/error': typeof AuthErrorRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/welcome': typeof AuthWelcomeRoute
  '/_public/': typeof PublicIndexRoute
  '/_private/admin/cards': typeof PrivateAdminCardsRoute
  '/_private/admin/devices': typeof PrivateAdminDevicesRoute
  '/_private/admin/logs': typeof PrivateAdminLogsRoute
  '/_private/admin/': typeof PrivateAdminIndexRoute
  '/_private/admin/timetable/import': typeof PrivateAdminTimetableImportRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/admin'
    | '/proba'
    | '/auth/error'
    | '/auth/login'
    | '/auth/welcome'
    | '/'
    | '/admin/cards'
    | '/admin/devices'
    | '/admin/logs'
    | '/admin/'
    | '/admin/timetable/import'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/proba'
    | '/auth/error'
    | '/auth/login'
    | '/auth/welcome'
    | '/'
    | '/admin/cards'
    | '/admin/devices'
    | '/admin/logs'
    | '/admin'
    | '/admin/timetable/import'
  id:
    | '__root__'
    | '/_private'
    | '/_public'
    | '/_private/admin'
    | '/_private/proba'
    | '/auth/error'
    | '/auth/login'
    | '/auth/welcome'
    | '/_public/'
    | '/_private/admin/cards'
    | '/_private/admin/devices'
    | '/_private/admin/logs'
    | '/_private/admin/'
    | '/_private/admin/timetable/import'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  PrivateRouteRoute: typeof PrivateRouteRouteWithChildren
  PublicRouteRoute: typeof PublicRouteRouteWithChildren
  AuthErrorRoute: typeof AuthErrorRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthWelcomeRoute: typeof AuthWelcomeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof PublicRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_private': {
      id: '/_private'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof PrivateRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/auth/welcome': {
      id: '/auth/welcome'
      path: '/auth/welcome'
      fullPath: '/auth/welcome'
      preLoaderRoute: typeof AuthWelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/error': {
      id: '/auth/error'
      path: '/auth/error'
      fullPath: '/auth/error'
      preLoaderRoute: typeof AuthErrorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_private/proba': {
      id: '/_private/proba'
      path: '/proba'
      fullPath: '/proba'
      preLoaderRoute: typeof PrivateProbaRouteImport
      parentRoute: typeof PrivateRouteRoute
    }
    '/_private/admin': {
      id: '/_private/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof PrivateAdminRouteRouteImport
      parentRoute: typeof PrivateRouteRoute
    }
    '/_private/admin/': {
      id: '/_private/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof PrivateAdminIndexRouteImport
      parentRoute: typeof PrivateAdminRouteRoute
    }
    '/_private/admin/logs': {
      id: '/_private/admin/logs'
      path: '/logs'
      fullPath: '/admin/logs'
      preLoaderRoute: typeof PrivateAdminLogsRouteImport
      parentRoute: typeof PrivateAdminRouteRoute
    }
    '/_private/admin/devices': {
      id: '/_private/admin/devices'
      path: '/devices'
      fullPath: '/admin/devices'
      preLoaderRoute: typeof PrivateAdminDevicesRouteImport
      parentRoute: typeof PrivateAdminRouteRoute
    }
    '/_private/admin/cards': {
      id: '/_private/admin/cards'
      path: '/cards'
      fullPath: '/admin/cards'
      preLoaderRoute: typeof PrivateAdminCardsRouteImport
      parentRoute: typeof PrivateAdminRouteRoute
    }
    '/_private/admin/timetable/import': {
      id: '/_private/admin/timetable/import'
      path: '/timetable/import'
      fullPath: '/admin/timetable/import'
      preLoaderRoute: typeof PrivateAdminTimetableImportRouteImport
      parentRoute: typeof PrivateAdminRouteRoute
    }
  }
}

interface PrivateAdminRouteRouteChildren {
  PrivateAdminCardsRoute: typeof PrivateAdminCardsRoute
  PrivateAdminDevicesRoute: typeof PrivateAdminDevicesRoute
  PrivateAdminLogsRoute: typeof PrivateAdminLogsRoute
  PrivateAdminIndexRoute: typeof PrivateAdminIndexRoute
  PrivateAdminTimetableImportRoute: typeof PrivateAdminTimetableImportRoute
}

const PrivateAdminRouteRouteChildren: PrivateAdminRouteRouteChildren = {
  PrivateAdminCardsRoute: PrivateAdminCardsRoute,
  PrivateAdminDevicesRoute: PrivateAdminDevicesRoute,
  PrivateAdminLogsRoute: PrivateAdminLogsRoute,
  PrivateAdminIndexRoute: PrivateAdminIndexRoute,
  PrivateAdminTimetableImportRoute: PrivateAdminTimetableImportRoute,
}

const PrivateAdminRouteRouteWithChildren =
  PrivateAdminRouteRoute._addFileChildren(PrivateAdminRouteRouteChildren)

interface PrivateRouteRouteChildren {
  PrivateAdminRouteRoute: typeof PrivateAdminRouteRouteWithChildren
  PrivateProbaRoute: typeof PrivateProbaRoute
}

const PrivateRouteRouteChildren: PrivateRouteRouteChildren = {
  PrivateAdminRouteRoute: PrivateAdminRouteRouteWithChildren,
  PrivateProbaRoute: PrivateProbaRoute,
}

const PrivateRouteRouteWithChildren = PrivateRouteRoute._addFileChildren(
  PrivateRouteRouteChildren,
)

interface PublicRouteRouteChildren {
  PublicIndexRoute: typeof PublicIndexRoute
}

const PublicRouteRouteChildren: PublicRouteRouteChildren = {
  PublicIndexRoute: PublicIndexRoute,
}

const PublicRouteRouteWithChildren = PublicRouteRoute._addFileChildren(
  PublicRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  PrivateRouteRoute: PrivateRouteRouteWithChildren,
  PublicRouteRoute: PublicRouteRouteWithChildren,
  AuthErrorRoute: AuthErrorRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthWelcomeRoute: AuthWelcomeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
