-- API keys previously stored a raw SHA-256 hash of the secret in `key_hash`.
-- SHA-256 is too fast/weak for credential storage and was flagged by CodeQL.
-- We now store a scrypt-derived key (`salt:keyHex`). Scrypt is non-reversible,
-- so the old SHA-256 hashes cannot be migrated. Drop and recreate the column
-- to clear the now-invalid hashes; existing keys must be regenerated by users.
ALTER TABLE "api_key" DROP CONSTRAINT "api_key_key_hash_unique";--> statement-breakpoint
ALTER TABLE "api_key" DROP COLUMN "key_hash";--> statement-breakpoint
ALTER TABLE "api_key" ADD COLUMN "key_hash" text NOT NULL;--> statement-breakpoint
ALTER TABLE "api_key" ADD CONSTRAINT "api_key_key_hash_unique" UNIQUE("key_hash");
