CREATE TABLE "wifi_auth_log" (
	"failure_reason" text,
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "wifi_auth_log_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"mac_address" text NOT NULL,
	"nas_ip_address" text,
	"nas_mac_address" text,
	"result" boolean NOT NULL,
	"timestamp" timestamp DEFAULT now() NOT NULL,
	"username" text NOT NULL,
	"wifi_user_id" uuid
);
--> statement-breakpoint
CREATE TABLE "wifi_device" (
	"admin_notes" text,
	"banned" boolean DEFAULT false NOT NULL,
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"last_active_at" timestamp,
	"mac_address" text NOT NULL,
	"nickname" text,
	"reported_hostname" text,
	"wifi_user_id" uuid,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "wifi_device_mac_address_unique" UNIQUE("mac_address")
);
--> statement-breakpoint
CREATE TABLE "wifi_nas" (
	"comment" text,
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"ip_address" text NOT NULL,
	"mac_address" text NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "wifi_nas_mac_address_unique" UNIQUE("mac_address")
);
--> statement-breakpoint
CREATE TABLE "wifi_role_speed_profile" (
	"priority" integer DEFAULT 0 NOT NULL,
	"role_name" text PRIMARY KEY NOT NULL,
	"speed_profile_id" text NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "wifi_speed_profile" (
	"download_speed_mbps" integer,
	"id" text PRIMARY KEY NOT NULL,
	"is_wlan_default" boolean DEFAULT false NOT NULL,
	"name" text NOT NULL,
	"synced_at" timestamp DEFAULT now() NOT NULL,
	"upload_speed_mbps" integer
);
--> statement-breakpoint
CREATE TABLE "wifi_user" (
	"allowed_mac_addresses" text[],
	"banned" boolean DEFAULT false NOT NULL,
	"comment" text,
	"created_by" uuid NOT NULL,
	"encrypted_password" text NOT NULL,
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"salt" text NOT NULL,
	"speed_profile_id" text,
	"user_id" uuid,
	"username" text NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "wifi_user_username_unique" UNIQUE("username")
);
--> statement-breakpoint
ALTER TABLE "wifi_auth_log" ADD CONSTRAINT "wifi_auth_log_wifi_user_id_wifi_user_id_fk" FOREIGN KEY ("wifi_user_id") REFERENCES "public"."wifi_user"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "wifi_device" ADD CONSTRAINT "wifi_device_wifi_user_id_wifi_user_id_fk" FOREIGN KEY ("wifi_user_id") REFERENCES "public"."wifi_user"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "wifi_role_speed_profile" ADD CONSTRAINT "wifi_role_speed_profile_speed_profile_id_wifi_speed_profile_id_fk" FOREIGN KEY ("speed_profile_id") REFERENCES "public"."wifi_speed_profile"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "wifi_user" ADD CONSTRAINT "wifi_user_user_id_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."user"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "wifi_auth_log_timestamp_idx" ON "wifi_auth_log" USING btree ("timestamp");--> statement-breakpoint
CREATE INDEX "wifi_auth_log_username_idx" ON "wifi_auth_log" USING btree ("username");--> statement-breakpoint
CREATE INDEX "wifi_auth_log_mac_address_idx" ON "wifi_auth_log" USING btree ("mac_address");--> statement-breakpoint
CREATE UNIQUE INDEX "wifi_device_mac_address_idx" ON "wifi_device" USING btree ("mac_address");--> statement-breakpoint
CREATE INDEX "wifi_device_wifi_user_id_idx" ON "wifi_device" USING btree ("wifi_user_id");--> statement-breakpoint
CREATE UNIQUE INDEX "wifi_nas_mac_address_idx" ON "wifi_nas" USING btree ("mac_address");--> statement-breakpoint
CREATE UNIQUE INDEX "wifi_nas_ip_address_idx" ON "wifi_nas" USING btree ("ip_address");--> statement-breakpoint
CREATE INDEX "wifi_role_speed_profile_role_name_idx" ON "wifi_role_speed_profile" USING btree ("role_name");--> statement-breakpoint
CREATE UNIQUE INDEX "wifi_user_username_idx" ON "wifi_user" USING btree ("username");--> statement-breakpoint
CREATE INDEX "wifi_user_user_id_idx" ON "wifi_user" USING btree ("user_id");