/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as ClientRouteImport } from './routes/_client/route'
import { Route as HomeIndexImport } from './routes/home/index'
import { Route as ClientIndexImport } from './routes/_client/index'
import { Route as ClientAuthIndexImport } from './routes/_client/auth/index'
import { Route as ClientAuthVerifyImport } from './routes/_client/auth/verify'
import { Route as ClientAuthOnboardingImport } from './routes/_client/auth/onboarding'

// Create/Update Routes

const ClientRouteRoute = ClientRouteImport.update({
  id: '/_client',
  getParentRoute: () => rootRoute,
} as any)

const HomeIndexRoute = HomeIndexImport.update({
  id: '/home/',
  path: '/home/',
  getParentRoute: () => rootRoute,
} as any)

const ClientIndexRoute = ClientIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ClientRouteRoute,
} as any)

const ClientAuthIndexRoute = ClientAuthIndexImport.update({
  id: '/auth/',
  path: '/auth/',
  getParentRoute: () => ClientRouteRoute,
} as any)

const ClientAuthVerifyRoute = ClientAuthVerifyImport.update({
  id: '/auth/verify',
  path: '/auth/verify',
  getParentRoute: () => ClientRouteRoute,
} as any)

const ClientAuthOnboardingRoute = ClientAuthOnboardingImport.update({
  id: '/auth/onboarding',
  path: '/auth/onboarding',
  getParentRoute: () => ClientRouteRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_client': {
      id: '/_client'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof ClientRouteImport
      parentRoute: typeof rootRoute
    }
    '/_client/': {
      id: '/_client/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ClientIndexImport
      parentRoute: typeof ClientRouteImport
    }
    '/home/': {
      id: '/home/'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeIndexImport
      parentRoute: typeof rootRoute
    }
    '/_client/auth/onboarding': {
      id: '/_client/auth/onboarding'
      path: '/auth/onboarding'
      fullPath: '/auth/onboarding'
      preLoaderRoute: typeof ClientAuthOnboardingImport
      parentRoute: typeof ClientRouteImport
    }
    '/_client/auth/verify': {
      id: '/_client/auth/verify'
      path: '/auth/verify'
      fullPath: '/auth/verify'
      preLoaderRoute: typeof ClientAuthVerifyImport
      parentRoute: typeof ClientRouteImport
    }
    '/_client/auth/': {
      id: '/_client/auth/'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof ClientAuthIndexImport
      parentRoute: typeof ClientRouteImport
    }
  }
}

// Create and export the route tree

interface ClientRouteRouteChildren {
  ClientIndexRoute: typeof ClientIndexRoute
  ClientAuthOnboardingRoute: typeof ClientAuthOnboardingRoute
  ClientAuthVerifyRoute: typeof ClientAuthVerifyRoute
  ClientAuthIndexRoute: typeof ClientAuthIndexRoute
}

const ClientRouteRouteChildren: ClientRouteRouteChildren = {
  ClientIndexRoute: ClientIndexRoute,
  ClientAuthOnboardingRoute: ClientAuthOnboardingRoute,
  ClientAuthVerifyRoute: ClientAuthVerifyRoute,
  ClientAuthIndexRoute: ClientAuthIndexRoute,
}

const ClientRouteRouteWithChildren = ClientRouteRoute._addFileChildren(
  ClientRouteRouteChildren,
)

export interface FileRoutesByFullPath {
  '': typeof ClientRouteRouteWithChildren
  '/': typeof ClientIndexRoute
  '/home': typeof HomeIndexRoute
  '/auth/onboarding': typeof ClientAuthOnboardingRoute
  '/auth/verify': typeof ClientAuthVerifyRoute
  '/auth': typeof ClientAuthIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof ClientIndexRoute
  '/home': typeof HomeIndexRoute
  '/auth/onboarding': typeof ClientAuthOnboardingRoute
  '/auth/verify': typeof ClientAuthVerifyRoute
  '/auth': typeof ClientAuthIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/_client': typeof ClientRouteRouteWithChildren
  '/_client/': typeof ClientIndexRoute
  '/home/': typeof HomeIndexRoute
  '/_client/auth/onboarding': typeof ClientAuthOnboardingRoute
  '/_client/auth/verify': typeof ClientAuthVerifyRoute
  '/_client/auth/': typeof ClientAuthIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '' | '/' | '/home' | '/auth/onboarding' | '/auth/verify' | '/auth'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/home' | '/auth/onboarding' | '/auth/verify' | '/auth'
  id:
    | '__root__'
    | '/_client'
    | '/_client/'
    | '/home/'
    | '/_client/auth/onboarding'
    | '/_client/auth/verify'
    | '/_client/auth/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  ClientRouteRoute: typeof ClientRouteRouteWithChildren
  HomeIndexRoute: typeof HomeIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  ClientRouteRoute: ClientRouteRouteWithChildren,
  HomeIndexRoute: HomeIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_client",
        "/home/"
      ]
    },
    "/_client": {
      "filePath": "_client/route.tsx",
      "children": [
        "/_client/",
        "/_client/auth/onboarding",
        "/_client/auth/verify",
        "/_client/auth/"
      ]
    },
    "/_client/": {
      "filePath": "_client/index.tsx",
      "parent": "/_client"
    },
    "/home/": {
      "filePath": "home/index.tsx"
    },
    "/_client/auth/onboarding": {
      "filePath": "_client/auth/onboarding.tsx",
      "parent": "/_client"
    },
    "/_client/auth/verify": {
      "filePath": "_client/auth/verify.tsx",
      "parent": "/_client"
    },
    "/_client/auth/": {
      "filePath": "_client/auth/index.tsx",
      "parent": "/_client"
    }
  }
}
ROUTE_MANIFEST_END */
