name: Lint

on:
  push:
    branches: ['main', 'development']

jobs:
  lint:
    name: Run Biome Linter and Formatter Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Bun
        uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Run Biome Check
        run: bun run check:ro

      - name: Run sherif
        run: bun x sherif
